name: $(date:yyyy.MM.dd)$(rev:.r)

trigger:
  batch: true
  branches: 
    include: 
      - main
  paths:
    include:
      - /Innovian.Dapr.Workflow.RegistrationAspect
      - /Innovian.Dapr.Workflow.RegistrationAspect.AspectTests
stages:
- stage: Test
  jobs:
  - job:
    workspace:
      clean: all
    pool: 
      name: AzureBuildServers
      demands: Agent.OS -equals Windows_NT
    variables:
    - name: BuildNumber
      value: $(Build.BuildNumber)
    - name: ProjectName
      value: Innovian.Dapr.Workflow.RegistrationAspect
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.x'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        projects: '**/$(ProjectName).csproj'
        noCache: true
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: '**/$(ProjectName).csproj'
        arguments: '--no-restore'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: 'test'
        projects: '**/$(ProjectName).Tests.csproj'    
- stage: Deployment
  dependsOn: Test
  jobs:
  - deployment: NugetDeployment
    displayName: "Deploying to NuGet"
    environment: "Public NuGet"
    pool: 
      name: AzureBuildServers
      demands: Agent.OS -equals Windows_NT
  - job:
    variables:
    - name: BuildNumber
      value: $(Build.BuildNumber)
    - name: ProjectName
      value: Innovian.Dapr.Workflow.RegistrationAspect
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.x'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        projects: '**/$(ProjectName).csproj'
        noCache: true
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: '**/$(ProjectName).csproj'
        arguments: '--no-restore'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: 'pack'
        packagesToPack: '**/$(ProjectName).csproj'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'BuildNumber'
    - task: NuGetCommand@2
      displayName: 'Push to NuGet.org'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'InnovianNuget'
